"""
從本機資料庫遷移到遠端資料庫
"""
import psycopg2
from psycopg2 import sql
import subprocess
import os

# 本機資料庫
local_host = "localhost"
local_port = 5432
local_db = "pa64_dev"
local_user = "dev"
local_password = "dev123"

# 遠端資料庫
remote_host = "10.1.0.20"
remote_port = 5433
remote_db = "pa64_dev"
remote_user = "admin"
remote_password = "!DC1qaz2wsx"

backup_file = "W:\\P-PA6.4\\pa64_dev_backup.sql"

print("="*70)
print("資料庫遷移工具")
print("="*70)

# 步驟 1: 備份本機資料庫
print("\n[1/4] 備份本機資料庫...")
print(f"      來源: {local_host}:{local_port}/{local_db}")
print(f"      備份檔: {backup_file}")

try:
    # 設定環境變數
    env = os.environ.copy()
    env['PGPASSWORD'] = local_password

    # 執行 pg_dump
    cmd = [
        'pg_dump',
        '-h', local_host,
        '-p', str(local_port),
        '-U', local_user,
        '-d', local_db,
        '-f', backup_file,
        '--no-owner',
        '--no-acl',
        '-v'
    ]

    result = subprocess.run(cmd, env=env, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"      錯誤: {result.stderr}")
        raise Exception("備份失敗")

    # 檢查檔案大小
    file_size = os.path.getsize(backup_file)
    print(f"      備份完成！檔案大小: {file_size:,} bytes ({file_size/1024/1024:.2f} MB)")

except FileNotFoundError:
    print("      pg_dump 不在 PATH 中，嘗試使用 Python 直接複製...")

    # 使用 Python 直接複製資料庫結構和資料
    try:
        # 連線到本機
        local_conn = psycopg2.connect(
            host=local_host,
            port=local_port,
            database=local_db,
            user=local_user,
            password=local_password
        )

        local_cur = local_conn.cursor()

        # 取得資料庫的 DDL
        print("      正在取得資料庫結構...")

        # 建立 SQL 備份檔
        with open(backup_file, 'w', encoding='utf-8') as f:
            # 寫入標頭
            f.write("-- PostgreSQL Database Backup\n")
            f.write(f"-- Source: {local_host}:{local_port}/{local_db}\n")
            f.write(f"-- Generated by Python migration script\n\n")

            # 取得所有表名
            local_cur.execute("""
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = 'public'
                ORDER BY tablename;
            """)

            tables = [row[0] for row in local_cur.fetchall()]
            print(f"      找到 {len(tables)} 個表")

            for table in tables:
                print(f"        備份表: {table}")

                # 取得表結構
                local_cur.execute(f"""
                    SELECT
                        'CREATE TABLE ' || quote_ident(tablename) || ' (' ||
                        string_agg(
                            quote_ident(column_name) || ' ' || data_type ||
                            CASE
                                WHEN character_maximum_length IS NOT NULL
                                THEN '(' || character_maximum_length || ')'
                                ELSE ''
                            END ||
                            CASE
                                WHEN is_nullable = 'NO' THEN ' NOT NULL'
                                ELSE ''
                            END,
                            ', '
                        ) || ');'
                    FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = '{table}'
                    GROUP BY tablename;
                """)

                create_stmt = local_cur.fetchone()
                if create_stmt:
                    f.write(f"\n-- Table: {table}\n")
                    f.write(f"DROP TABLE IF EXISTS {table} CASCADE;\n")
                    # 這裡需要更完整的DDL，暫時使用簡化版

                # 匯出資料
                local_cur.execute(f"SELECT * FROM {table};")
                rows = local_cur.fetchall()

                if rows:
                    # 取得欄位名稱
                    local_cur.execute(f"""
                        SELECT column_name
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = '{table}'
                        ORDER BY ordinal_position;
                    """)
                    columns = [row[0] for row in local_cur.fetchall()]

                    f.write(f"\n-- Data for table: {table}\n")
                    for row in rows:
                        values = []
                        for val in row:
                            if val is None:
                                values.append('NULL')
                            elif isinstance(val, str):
                                # 轉義單引號
                                escaped = val.replace("'", "''")
                                values.append(f"'{escaped}'")
                            elif isinstance(val, (int, float)):
                                values.append(str(val))
                            else:
                                values.append(f"'{str(val)}'")

                        cols_str = ', '.join(columns)
                        vals_str = ', '.join(values)
                        f.write(f"INSERT INTO {table} ({cols_str}) VALUES ({vals_str});\n")

        local_cur.close()
        local_conn.close()

        file_size = os.path.getsize(backup_file)
        print(f"      Python 備份完成！檔案大小: {file_size:,} bytes")

    except Exception as e:
        print(f"      Python 備份失敗: {e}")
        raise

except Exception as e:
    print(f"      備份失敗: {e}")
    exit(1)

# 步驟 2: 還原到遠端資料庫
print(f"\n[2/4] 還原到遠端資料庫...")
print(f"      目標: {remote_host}:{remote_port}/{remote_db}")

try:
    # 設定環境變數
    env = os.environ.copy()
    env['PGPASSWORD'] = remote_password

    # 執行 psql
    cmd = [
        'psql',
        '-h', remote_host,
        '-p', str(remote_port),
        '-U', remote_user,
        '-d', remote_db,
        '-f', backup_file,
        '-v', 'ON_ERROR_STOP=1'
    ]

    result = subprocess.run(cmd, env=env, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"      錯誤: {result.stderr}")
        raise Exception("還原失敗")

    print(f"      還原完成！")

except FileNotFoundError:
    print("      psql 不在 PATH 中，使用 Python 直接執行...")

    try:
        # 連線到遠端
        remote_conn = psycopg2.connect(
            host=remote_host,
            port=remote_port,
            database=remote_db,
            user=remote_user,
            password=remote_password
        )

        remote_cur = remote_conn.cursor()

        # 讀取並執行 SQL 檔案
        print("      正在執行 SQL...")
        with open(backup_file, 'r', encoding='utf-8') as f:
            sql_content = f.read()

            # 分割成個別語句並執行
            statements = sql_content.split(';')
            for i, stmt in enumerate(statements):
                stmt = stmt.strip()
                if stmt and not stmt.startswith('--'):
                    try:
                        remote_cur.execute(stmt)
                    except Exception as e:
                        print(f"        警告: 語句 {i+1} 執行失敗: {e}")

        remote_conn.commit()
        remote_cur.close()
        remote_conn.close()

        print("      Python 還原完成！")

    except Exception as e:
        print(f"      Python 還原失敗: {e}")
        raise

except Exception as e:
    print(f"      還原失敗: {e}")
    exit(1)

# 步驟 3: 驗證資料
print(f"\n[3/4] 驗證遠端資料庫...")

try:
    # 連線本機和遠端
    local_conn = psycopg2.connect(
        host=local_host, port=local_port,
        database=local_db, user=local_user, password=local_password
    )

    remote_conn = psycopg2.connect(
        host=remote_host, port=remote_port,
        database=remote_db, user=remote_user, password=remote_password
    )

    local_cur = local_conn.cursor()
    remote_cur = remote_conn.cursor()

    # 比較表數量
    local_cur.execute("SELECT COUNT(*) FROM pg_tables WHERE schemaname = 'public';")
    local_table_count = local_cur.fetchone()[0]

    remote_cur.execute("SELECT COUNT(*) FROM pg_tables WHERE schemaname = 'public';")
    remote_table_count = remote_cur.fetchone()[0]

    print(f"      本機表數量: {local_table_count}")
    print(f"      遠端表數量: {remote_table_count}")

    if local_table_count == remote_table_count:
        print("      ✓ 表數量一致")
    else:
        print("      ✗ 警告: 表數量不一致")

    local_cur.close()
    local_conn.close()
    remote_cur.close()
    remote_conn.close()

    print("      驗證完成！")

except Exception as e:
    print(f"      驗證失敗: {e}")

# 完成
print(f"\n[4/4] 遷移完成！")
print("\n" + "="*70)
print("SUCCESS! 資料庫遷移成功！")
print("="*70)

print(f"\n遠端資料庫連線字串:")
print(f"postgresql://{remote_user}:{remote_password}@{remote_host}:{remote_port}/{remote_db}")
